export default [
    {id:661, musica: 'Medo da Chuva', artista: 'Falamansa', tagprimaria:'Forró', tagsecundaria: 'Pop'},
    {id:662, musica: 'Zóio de Lula', artista: 'Charlie Brown', tagprimaria:'Reggae', tagsecundaria: 'Rock'},
    {id:663, musica: 'Anunciação', artista: 'Alceu Valença', tagprimaria:'Baião', tagsecundaria: 'Pop'},
    {id:664, musica: 'Vapor Barato', artista: 'O Rappa', tagprimaria:'Reggae', tagsecundaria: 'Rock'},
    {id:665, musica: 'Maladragem', artista: 'Cassia Eller', tagprimaria:'Pop', tagsecundaria: 'Rock'},
    {id:666, musica: 'Eduardo e Mônica', artista: 'Legião Urbana', tagprimaria:'Pop', tagsecundaria: 'Rock'},
    {id:667, musica: 'Santeria', artista: 'Sublime', tagprimaria:'Reggae', tagsecundaria: 'Rock'},
    {id:6671, musica: 'Pinball Wizard', artista: 'The Who', tagprimaria:'Rock', tagsecundaria: 'Rock'},
    {id:6672, musica: 'I Want To Hold Your Hand', artista: 'The Beatles', tagprimaria:'Pop', tagsecundaria: 'Rock'},
    {id:616, musica: 'I Want To Break Free', artista: 'Queen', tagprimaria:'Pop', tagsecundaria: 'Rock'},
    {id:611, musica: 'Basket Case', artista: 'Green Day', tagprimaria:'Punk', tagsecundaria: 'Pop'},
    {id:612, musica: 'Medo da Chuva', artista: 'Falamansa', tagprimaria:'Forró', tagsecundaria: 'Pop'},
    {id:613, musica: 'Medo da Chuva', artista: 'Falamansa', tagprimaria:'Forró', tagsecundaria: 'Pop'},
    {id:614, musica: 'Medo da Chuva', artista: 'Falamansa', tagprimaria:'Forró', tagsecundaria: 'Pop'},
    {id:615, musica: 'Medo da Chuva', artista: 'Falamansa', tagprimaria:'Forró', tagsecundaria: 'Pop'},
    {id:616, musica: 'Medo da Chuva', artista: 'Falamansa', tagprimaria:'Forró', tagsecundaria: 'Pop'},
    {id:617, musica: 'Medo da Chuva', artista: 'Falamansa', tagprimaria:'Forró', tagsecundaria: 'Pop'},
    {id:6171, musica: 'Medo da Chuva', artista: 'Falamansa', tagprimaria:'Forró', tagsecundaria: 'Pop'},
    {id:6172, musica: 'Medo da Chuva', artista: 'Falamansa', tagprimaria:'Forró', tagsecundaria: 'Pop'},
    {id:626, musica: 'Medo da Chuva', artista: 'Falamansa', tagprimaria:'Forró', tagsecundaria: 'Pop'},
    {id:621, musica: 'Medo da Chuva', artista: 'Falamansa', tagprimaria:'Forró', tagsecundaria: 'Pop'},
    {id:622, musica: 'Medo da Chuva', artista: 'Falamansa', tagprimaria:'Forró', tagsecundaria: 'Pop'},
    {id:623, musica: 'Medo da Chuva', artista: 'Falamansa', tagprimaria:'Forró', tagsecundaria: 'Pop'},
    {id:624, musica: 'Medo da Chuva', artista: 'Falamansa', tagprimaria:'Forró', tagsecundaria: 'Pop'},
    {id:625, musica: 'Medo da Chuva', artista: 'Falamansa', tagprimaria:'Forró', tagsecundaria: 'Pop'},
    {id:626, musica: 'Medo da Chuva', artista: 'Falamansa', tagprimaria:'Forró', tagsecundaria: 'Pop'},
    {id:627, musica: 'Medo da Chuva', artista: 'Falamansa', tagprimaria:'Forró', tagsecundaria: 'Pop'},
]