export default [
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Zóio de Lula', artista: 'Charlie Brown', tag1:'Reggae', tag2: 'Rock'},
    {musica: 'Anunciação', artista: 'Alceu Valença', tag1:'Baião', tag2: 'Pop'},
    {musica: 'Vapor Barato', artista: 'O Rappa', tag1:'Reggae', tag2: 'Rock'},
    {musica: 'Maladragem', artista: 'Cassia Eller', tag1:'Pop', tag2: 'Rock'},
    {musica: 'Eduardo e Mônica', artista: 'Legião Urbana', tag1:'Pop', tag2: 'Rock'},
    {musica: 'Santeria', artista: 'Sublime', tag1:'Reggae', tag2: 'Rock'},
    {musica: 'Pinball Wizard', artista: 'The Who', tag1:'Rock', tag2: 'Rock'},
    {musica: 'I Want To Hold Your Hand', artista: 'The Beatles', tag1:'Pop', tag2: 'Rock'},
    {musica: 'I Want To Break Free', artista: 'Queen', tag1:'Pop', tag2: 'Rock'},
    {musica: 'Basket Case', artista: 'Green Day', tag1:'Punk', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
    {musica: 'Medo da Chuva', artista: 'Falamansa', tag1:'Forró', tag2: 'Pop'},
];